version: 2.1
orbs:
  node: circleci/node@1.1.6
  coveralls: coveralls/coveralls@1.0.5
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm install && npm run test
      - coveralls/upload
workflows:
    build-and-test:
      jobs:
        - build-and-test